### ISSUE TITLE
Screen edges do not register mouse clicks after using this script

### ISSUE THREAD

**Issue by k-amin07** [Aetf/kwin-maxmize-to-new-desktop#11]
Hi, I have a weird problem that I am convinced is related to this script. I started noticing that clicks would not get registered near the edge of the screen (for example the scrollbar in a maximized browser becomes unclickable). I tried disabling the script and the problem stopped appearing. 

[Here is a screenshot](https://ibb.co/t3M6JSd) of the issue. As you can see, the icon did not get highlighted while the cursor was closer to the screen edge. I have tried MACsimize which is a fork of this work (though with less available configurations) and the problem appeared with it too.

**Comment by k-amin07** [comment]
I am using Artix Linux (based on arch), I have a latte panel on the top and icons on the edges of the panel remain clickable.

**Comment by Aetf** [comment]
Do you have other scrips running? This script only adds a few hooks, and essentially does nothing if there's no window changes.

Also, did you have this problem with a previous kwin? Also possible to be caused by kwin scripting in general.

**Comment by k-amin07** [comment]
I have only recently installed this script so I dont know if it was working with the previous kwin versions. Other kwin scripts that I have installed are:

Force Blur, Latte Windows Colors, [Parachute](https://github.com/tcorreabr/Parachute) and Sticky windows snapping. 

and I am using virtual desktop bar applet to manage my virtual desktops.

I agree that the problem logically does not make sense, but for some reason as soon as I maximize a window and restore it with this script enabled, my clicks stop getting registered near the left and right edge of screen.

**Comment by k-amin07** [comment]
I realized while typing the previous response that it may have something to do with the virtual desktop bar settings I am using and after some testing, that does appear to be the case. It has a setting for dynamic desktops. Enabling it resolves the issue but then the virtual desktops do not switch automatically upon maximizing the window. I guess there are limitations to everything, will probably have to use some other virtual desktop manager.
