### ISSUE TITLE
Simply does not work

### ISSUE THREAD

**Issue by doordormeta** [Aetf/kwin-maxmize-to-new-desktop#12]
I have it installed but it does nothing.

What do you need to proceed further with this?

**Comment by doordormeta** [comment]
Turns out the script is not compatible with hide titlebars kwin rule.

When the titlebar is hidden when maximized, the maximized window is not put to the new workspace.

When the titlebar is not hidden when maximized, the window is put to the new workspace.

I have played with my girlfriend's mac and when window is maximized it behaves like this:
- Window is put to a new workspace.
- The titlebar is hidden.
- The top bar is hidden hidden.

- When you mouseover for the top bar to appear, the window gains titlebar and dodges the top bar.
- When you move the cursor away from the top bar it disappears along with the titlebar.

This is what I would like to achieve but the scripts are not compatible

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by doordormeta** [comment]
I mean 'hide titles' kwin script

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Aetf** [comment]
AFAIW there shouldn't be anything conflicting between the two.

I'm using a similar setup where the title bar of maximized windows is removed. But I'm using latte dock's borderless layout to achieve this.

It'd be really helpful if you could post the debug log so I can take a look at this

**Comment by hugeblank** [comment]
> Did you use fullscreen or maximize? By default the script is triggered on fullscreen: see the [note](https://github.com/Aetf/kwin-maxmize-to-new-desktop#feature) here.

I'm pretty sure this person missed the note. It does work perfectly when making the config directory. 

I'm of the opinion that by default it should do this for when one presses the maximize button. The name is maximize to new desktop, not fullscreen to new desktop after all. :P

**Comment by Aetf** [comment]
Closing as stale.
