### ISSUE TITLE
Virtual desktop is not removed on window close

### ISSUE THREAD

**Issue by IldarGainanov** [Aetf/kwin-maxmize-to-new-desktop#14]
The title says it all. 

I've poked around the source code to find the cause of the issue and found out that client becomes `undefined` after `windowClosed` signal is sent, causing errors.

code:
```js
closed: function(client) {
    log('handle remove');
    log(client);
    ...
}
```
output:
```
js: KWinMax2NewVirtualDesktop: handle remove
js: KWinMax2NewVirtualDesktop: undefined
...
file:///home/ildar/.local/share/plasma-interactiveconsole/interactiveconsoleautosave.js:81: TypeError: Cannot read property 'windowId' of undefined
```

Maybe the script was broken by a KDE update?

I can provide more information about my system if needed.

**Comment by Aetf** [comment]
Thanks for the report and investigation. I just noticed the same issue. I'll look into this shortly.

**Comment by Aetf** [comment]
Looks like an upstream KWin bug, I just reported it: https://bugs.kde.org/show_bug.cgi?id=449181

For now, I implemented a workaround it in ae55754

**Comment by PH7-Jack** [comment]
I have the same issue

**Comment by Aetf** [comment]
@PH7-Jack commenting on a closed issue can hardly have your problem solved. Especially this one is specifically about an upstream bug that has been worked around.

Please open a new issues with more information if the problem persists. Thanks.
