### ISSUE TITLE
It will crash kwin on opensuse leap 15.5/ tumbleweed if the kde native app like dolphin closed with maximized state

### ISSUE THREAD

**Issue by sauntor** [Aetf/kwin-maxmize-to-new-desktop#20]
As the title says, and details is here: https://bugzilla.opensuse.org/show_bug.cgi?id=1212921

I submitted it to openSUSE, but no one answers

**Comment by Aetf** [comment]
You may have better luck reporting to KDE directly: http://bugs.kde.org

Also https://community.kde.org/KWin/Debugging

I'm closing this as there's little we can do in the script.

**Comment by sauntor** [comment]
> You may have better luck reporting to KDE directly: http://bugs.kde.org
> 
> Also https://community.kde.org/KWin/Debugging
> 
> I'm closing this as there's little we can do in the script.

Thanks. I find it may be caused by `Desktop Effects` -> `Window Open/Close Animation`,  I pick an effect developed by KDE team, then this problem will disappear. Maybe I should report it to that `Effect` plugin developer.

**Comment by Aetf** [comment]
Kwin ideally shouldn't crash given any script/effect plugin. If you could reliably reproduce the crash, it doesn't harm to also report to Kwin :)
