### ISSUE TITLE
When set to create new desktop on maximize, it doesn't create a desktop when window starts maximized

### ISSUE THREAD

**Issue by d86leader** [Aetf/kwin-maxmize-to-new-desktop#4]
This is annoying with the following example:
1) Open a dolphin window
2) Maximize it - a new desktop appears
3) Close it - the new desktop disappears
4) Open dolphin again - it starts maximized but new desktop does not appear

**Comment by Aetf** [comment]
It's indeed an inconsistency of the behaviour.

However, KWin doesn't emit `clientMaximized` signal for new windows. And there is no direct way to query maximize state of a window.

It might be possible to directly compare the geometry, but I'm not sure how reliable that is. I need to think about it.

**Comment by d86leader** [comment]
I went looking and found this wonderful bug report: https://bugs.kde.org/show_bug.cgi?id=403071

**Comment by d86leader** [comment]
It seems this won't help. Looking through the api now, they made maximization into a function, not a property. So you can now manually maximize a window, but still can't check if it's maximized currently.

Unless the window now also emits the clientMaximized upon creation. If that were the case, this functionality would work already. I assume it does not?

**Comment by d86leader** [comment]
I myself now use the extension you can find pinned in my profile, and manually move windows around. It's not ideal, but it's something

**Comment by d86leader** [comment]
That's fullscreen, not maximized. The fullscreen functionality worked from the start.

**Comment by d86leader** [comment]
That might be because game engines sometimes use funky hacks to bypass your compositor, so it might not know about tha game window state. Try it with a regular window and pressing F11 instead, and open a separate issue if that doesn't work: let's keep this one tracking the maximization problem.

In any case, I don't know what I'm talking about, I don't even use this extension anymore, and I haven't touched kwin scripting api in two years ;)
