### ISSUE TITLE
Fullscreenize to other screen (TV, projector).

### ISSUE THREAD

**Issue by Polisson** [Aetf/kwin-maxmize-to-new-desktop#5]
I come up with feature request: what about building a script which moves window to special purpose screen when it became fullscreen mode?
Example of such apps would be: browsers, media players, (Kodi), games, presentation apps/.pdfs etc. etc.
Every time when fullscreen app is launched or became fullscreen (using built in mechanism or by window manager) Kwin would send it to another, earlier chosen particular screen.
It would be very useful for those who use TV as home screens with their laptops or during presentation, when only presented media are sent to main projector.

**Comment by Aetf** [comment]
That's out of the scope of this project, sorry. But you are welcome to fork and implement what you want ;)
