### ISSUE TITLE
KDE crashed when fullscreen/maximized window is closed directly from the new workspace

### ISSUE THREAD

**Issue by Zwambro** [Aetf/kwin-maxmize-to-new-desktop#6]
Hey, I'm facing this problem when I'm closing the new Maximized window from the new created workspace the KDE crashing, or freezing then closing the window without deleting the workspace. that's happened after the new KDE updates. 
I'm using KDE 5.18.3
Thank you in advance.
[kwin_x11-20200323-235804.kcrash.txt](https://github.com/Aetf/kwin-maxmize-to-new-desktop/files/4372331/kwin_x11-20200323-235804.kcrash.txt)
That's the log if you need it

**Comment by Aetf** [comment]
Hi, sorry for the late reply.

This is most likely a KWin problem given the crash. While I may be able to work around this in the script, I don't have much time to investigate right now :/

I'd suggest you report the bug to KWin [bug tracker](https://bugs.kde.org/enter_bug.cgi?product=kwin) so they can fix the crash.

Thanks for taking the effort to report this!
