### ISSUE TITLE
Maximize to another display.

### ISSUE THREAD

**Issue by Polisson** [Aetf/kwin-maxmize-to-new-desktop#8]
I don't see any feature requests or enhancements, so I dare to post one:
make ability to move a window which became fullscreened  to another displaying device (not workspace).
This display would be selectable from setting (if there is more than two).

When: 
- browsing the net and finding a video and hitting F11 or 
- need to make fullscreen dolphin, or 
- making presentation (powerPoint, images, pdfs, etc.)

the script sends window to that other screen (TV, projector, other room).

**Comment by Aetf** [comment]
You already posted one :) See #5.

As I said, this is pretty much out of the scope of this project, which is simply a small script to mimic the OSX behavior. However, I can see why this may be helpful in some cases. This time I'll leave this open, though. So if anyone wants to implement it, they are welcome to submit a PR.

**Comment by Polisson** [comment]
Aahh yes..... I'm embarrassed now 😅... sorry.
Someone forked your work few years ago and made me confused. His script resembled exact functionality as yours and abandoned it likely, so I thought there is space for this idea.
Thanks for deeper explanation of your goals and vision.

**Comment by Aetf** [comment]
Close as it's unlikely this ever gets implemented.
