### ISSUE TITLE
Doesn't work properly

### ISSUE THREAD

**Issue by SylEleuth** [Aetf/kwin-maxmize-to-new-desktop#9]
Manjaro KDE Plasma 5.20.4
Version 0.2.1 installed via Get New Scripts
Fresh system installation.
Settings - maximize only

When using maximized, a new workspace opens and a window moves there, but new window is hidden under maximized one. The last changes were made 2 years ago but it stopped working for me months ago.

**Comment by Aetf** [comment]
Sorry, I'm not sure I understand your description. What do you mean by a new window is hidden under the maximized one? Is the maximized window moved to the new workspace? 

Given nothing changed in the script, there must be some changes in kwin caused this.

**Comment by SylEleuth** [comment]
I used it with Krohnkite (tiling manager emulator) and it worked like this - maximized window moves to a new workspace (that part works fine) and while there opening a new one should bring it on top (added as a tiling window with Krohnkite) but it stays hidden below the first one that was maximized. Focus is given to the the last opened window so I can close it with a key shortcut.

I've never used MacOS so I have no idea how it works there but it looks like kwin forces it to fill the whole space and staying above any new window. Or maybe it's the feature and it should be like that from the beginning?

**Comment by Aetf** [comment]
That's a bug in Krohnkite or kwin, then. This script doesn't touch anything related to window ordering.

**Comment by SylEleuth** [comment]
I didn't use Krohnkite while testing it so it's not that. Also, as I mentioned earlier, it's a fresh system installation.

**Comment by Aetf** [comment]
Have you tried disabling any scripts, and do everything manually? I.e. maxmize a window A, then create a new workspace, then move the window A to the new workspace, then open another window?

Does the window you maximize somehow has stay-on-top set?

**Comment by SylEleuth** [comment]
Well, I tested it again and I think You were right. Your script alone seems to work fine (although I'm 99,99% sure it didn't earlier, but it does now). In that case, as You said, it must be Krohnkite. Thank You for Your time.
